name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK (Java Development Kit) untuk Android build
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Install dependencies
      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk
          echo "y" | sdkmanager --sdk_root=$HOME/Android/Sdk "build-tools;30.0.3" "platforms;android-30" "platform-tools"

      # Build APK
      - name: Build APK
        run: |
          ./gradlew assembleRelease

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: app/build/outputs/apk/release/*.apk
